/**
 * Generates a version.ts file for a package using CalVer + commit count.
 * Usage: bun run scripts/generate-version.ts <package-path>
 * Example: bun run scripts/generate-version.ts packages/attention-requester
 */

import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const packagePath = process.argv[2];
if (!packagePath) {
	console.error("Usage: bun run scripts/generate-version.ts <package-path>");
	process.exit(1);
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const absolutePackagePath = resolve(repoRoot, packagePath);

const now = new Date();
const year = now.getFullYear();
const month = String(now.getMonth() + 1).padStart(2, "0");

const proc = Bun.spawnSync(["git", "rev-list", "--count", "HEAD", "--", packagePath], {
	cwd: repoRoot,
	env: { ...process.env },
});
const count = proc.stdout.toString().trim();

if (proc.exitCode !== 0 || !count) {
	console.error(`Failed to count commits for ${packagePath}`);
	process.exit(1);
}

const version = `${year}.${month}.${count.padStart(3, "0")}`;
const outputPath = resolve(absolutePackagePath, "src/lib/version.ts");

const content = `// Auto-generated by scripts/generate-version.ts — do not edit
export const VERSION = "${version}" as const;
`;

await Bun.write(outputPath, content);
console.log(`${outputPath} → ${version}`);
